name: tflite_audio
maintainer: Michael Nguyen
description: Tflite plugin for flutter. Can make audio classifications on both android and iOS using your own custom tflite model.
version: 0.1.6
homepage: https://github.com/Caldarie/flutter_tflite_audio

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  effective_dart: ^1.0.0
  
flutter:
  plugin:
    platforms:
      android:
        package: flutter.tflite_audio
        pluginClass: TfliteAudioPlugin
      ios:
        pluginClass: TfliteAudioPlugin
