name: tflite_audio
maintainer: Michael Nguyen
description: Audio classification Tflite package for flutter (iOS & Android). Can support Google Teachable Machine models. 
version: 0.2.2+4
homepage: https://github.com/Caldarie/flutter_tflite_audio

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  effective_dart: ^1.3.1
  flutter_test:
    sdk: flutter
  
flutter:
  plugin:
    platforms:
      android:
        package: flutter.tflite_audio
        pluginClass: TfliteAudioPlugin
      ios:
        pluginClass: TfliteAudioPlugin
